// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const root = path.dirname(fileURLToPath(import.meta.url));

config({ path: path.join(root, ".env") });
config({ path: path.join(root, ".env.local"), override: true });

function databaseUrlForCli(raw: string): string {
  const isLocal = /localhost|127\.0\.0\.1/i.test(raw);
  if (!isLocal) return raw;
  return raw
    .replace(/([?&])sslmode=[^&]*/gi, "$1")
    .replace(/[?&]$/, "")
    .replace(/\?&/, "?")
    .replace(/\?$/, "");
}

const databaseUrl = databaseUrlForCli(process.env["DATABASE_URL"]?.trim() ?? "");
if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL ontbreekt. Zet hem in .env.local (zie .env.local.example).",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
