-- Managed shop brands (merken) + product.brand_id.
-- Unique product.brand strings are backfilled into brands and linked.

create table if not exists public.brands (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  logo_url text,
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists brands_visible_sort_idx
  on public.brands (visible, sort_order);

alter table public.brands enable row level security;

alter table public.products
  add column if not exists brand_id integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_brand_id_fkey'
  ) then
    alter table public.products
      add constraint products_brand_id_fkey
      foreign key (brand_id) references public.brands(id) on delete set null;
  end if;
end
$$;

create index if not exists products_brand_id_idx
  on public.products (brand_id);

comment on table public.brands is
  'Beheerde merkenlijst; product.brand blijft de denormaliseerde naam voor zoeken/SEO.';

-- Slugify helper for backfill (NL-ish, no extension required).
create or replace function public._bergasports_brand_slug(raw text)
returns text
language sql
immutable
as $$
  select left(
    trim(both '-' from regexp_replace(
      translate(
        lower(trim(coalesce(raw, ''))),
        'áàäâãåéèëêíìïîóòöôõúùüûçñÿýšž',
        'aaaaaaeeeeiiiiooooouuuucnyyszz'
      ),
      '[^a-z0-9]+',
      '-',
      'g'
    )),
    80
  );
$$;

insert into public.brands (name, slug, visible, sort_order)
select src.name, src.slug, true, 0
from (
  select distinct on (public._bergasports_brand_slug(brand))
    trim(brand) as name,
    public._bergasports_brand_slug(brand) as slug
  from public.products
  where coalesce(trim(brand), '') <> ''
    and public._bergasports_brand_slug(brand) <> ''
  order by public._bergasports_brand_slug(brand), id
) src
on conflict (slug) do nothing;

insert into public.brands (name, slug, visible, sort_order)
values
  ('Colnago', 'colnago', true, 10),
  ('Orbea', 'orbea', true, 20),
  ('Basso', 'basso', true, 30),
  ('Cervélo', 'cervelo', true, 40),
  ('Cipollini', 'cipollini', true, 50),
  ('Titici', 'titici', true, 60),
  ('Sensa', 'sensa', true, 70),
  ('Scope', 'scope', true, 80),
  ('Nimbl', 'nimbl', true, 90),
  ('LaFuga', 'lafuga', true, 100),
  ('Double FF', 'double-ff', true, 110),
  ('KASK', 'kask', true, 120)
on conflict (slug) do nothing;

update public.products p
set brand_id = b.id
from public.brands b
where p.brand_id is null
  and coalesce(trim(p.brand), '') <> ''
  and public._bergasports_brand_slug(p.brand) = b.slug;

drop function if exists public._bergasports_brand_slug(text);
